![My Bio Image](assets/Barack%20passport.jpg)
title: Barack Omondi Odhiambo
logo: /assets/Barack%20passport.jpg
description: Digital & Graphic designer / Editor / Entrepreneur
theme: jekyll-theme-dinky 
